version: 0.2

env:
  variables:
    #IMAGE_REPO_NAME: "react-app"
    #IMAGE_TAG: "latest"
    # Optional: Uncomment and set these if not auto-populated by CodeBuild
    # AWS_DEFAULT_REGION: "us-east-1"  # Replace with your region
    # AWS_ACCOUNT_ID: "807034087511"  # Replace with your AWS account ID
  # Optional: Uncomment this ONLY if you need a Docker PAT for private registries (e.g., Docker Hub)
  # Ensure the secret exists in AWS Secrets Manager and your CodeBuild role has permissions!
  # secrets-manager:
 

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # Optional: If using a Docker PAT for private images, add login here (uncomment and adjust)
      # - echo Logging in to Docker Hub with PAT...
      # - docker login --username your-docker-username --password $DOCKER_PAT

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
